name: Build
on:
  push:
    branches:
      - main
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
  git-version:
    needs: checkout
    runs-on: ubuntu-latest
    steps:
      - run: |
          touch test.txt
          git status
          ls
